language: node_js
node_js:
  - '6.10'
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  bucket: $AWS_S3_BUCKET_NAME
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  'on':
    branch: master
env:
  global:
    - secure: >-
        i7Do+fVwsBMAi9qfn90AfcDFl6xwiq/SmFdjI4PT3zYI46Ey6qav/n69zQICJCjGFbPQ8GU9zpTRa4iQF1CVTj/kakIPPqEKIH3VFrvDUT7Kakz/cExn0owkswzXzWAO6VFBAIaMXKTFsA2PGcJ9Eo5pvqn81GcaMF31CMfWl8QcSzsfYA4SB4OqzTTBNrzlKLIppfkZUGfcA2z4dmSiLH57K1j66ekPcTNICr/bWXfgILbBSqaPbGRVPS3IYWmaLnN5iaTHiITohC32DK49ARrfK79BAIo67P9QKx3jS+kP54qY8JF51GvfZTFvHE8vb+j5E73GjUBKKD1HRaZWSdADK0QA1rxtwjLkAoKAHXv782ZLGRuh8+yRmY+rlmWfgKXFW6Pu0vQO/+z4xJgr2bzdfKLBa322p5llW5VimWztzZRVOGEXE6hzG1jiRaQ847E4yZWRnBRj8njtxEk8e14J9zpSFo3SuapS/5b+nt+bzSmOtBohd/Q/MB+iZRQkT9Dcc3l0BA9kdE72RXxs+fj4F5VbzYQweMEIB56CwX5C5UrtefUlUrDxjpK5GB/6AcoMCG/FZ40wfd9QjIbs+GeUTLvyQGsppydiuMLcAPX4pyPLrB20zmAesexkCwcan/fp6abCO8Lzdihdh1nyWz/qCl3RUb6WhQHmVtjJWiI=
    - secure: >-
        arKgyqoVjbWyz+a7hkNEIS2DrQZnSAimIfU9A5pApL4WqrGI1xnKjBgnBjvgW0+BdQi5av2Bv+5uznvB2HCWAGIvhgEv7Qh4JewgQNWBjvwj4SAOo0TdmW+n51Ngf+i+EeWOJ/WRX79IRM7W/yad6odoQifEuS4+9bAUmXfqtfnLL62GmsYEJ7kOzWIEyZwHRtGIH+Mgw2lcA5arPoJXuqCaX7qa70q8pnyK4LbEyY60tTfQ92ZAbNz5QWOrjaYjBMov3F3Yc371aNc5iDjDX0NHBE6QhrYLXb0qAT2XsrFSI0dVxHlp9AVeTjV9zl1ByKke0eEoFz6ZzguvFZig1n6CFCtcTy9pm9LKmMezqqgvGshikks7y4sVqQ/HoD9Mt6vG8kEyN+jJIcA8v0/8JWXVWCnGyvkS3Yyvil69fEuObyiKYTfmyH0PkY5lV9tnkH7TPYH0yS3AnUkRW7/ySEC3ZSL5AvGYyQeJYgropgv1ISyLjNqrxG9fxu1VeJNxFl+WoKOA3SVtdv9RzN8v+ZN3AY4noh72pLXF9v/xQH/aKkEyEhvHXa4NzvqOX0AwM9VIn3vg6vsqd21sOiZqX4joQ4noeGvSqAG/KMzGCVp6Xa4+7G3pjocCyySEMzRT0q6Amx5F5I0E7PTeVRlUywemBZzu6KgYaOYZuHkxBCk=
    - secure: >-
        YRauDa5T6NMW8Bcf7xcSJWguQm+1tr1dk4ToNiHJWdiHcAR+6AFEj7JVPQZbgSYog0ui6MA9ryurbnmKabwMPleHH077nOklvDek3TKn4CocrqJKY7QqYwgdyWpul1x/JoKVzK2yCXeVnle8SXznOz0S02BExjb1XBU3964L5TtQlKOFUVfstpSt3V1rBFnu9UNR2uxXJbwfAcj/AEXs9TJLN7e67FMlrkCioK9wqxJHVrC8Yr2O8eXHUUaRC/MyNug+Q/YNK+650pNUAKACeRWSkX+jz8lzHPZeHDvuAO38P+FdNfSSzA20T7zM8l3KwHXfib9NPMHwnTSS3S/hgQYPBNu292TWDj8/byt7iGZxyQ9iD9sdkkrccvFl80+GI4QJbVL9lekj2ZFnKzYy4WwY1KHea53IOQofTBeD/9rX0PMOEqE++H4p8140wXX0IY2/ho2lb4TWSGb7k55zmC0i/lA+qb6sj9zpdA/w5ZvHHSANJGfHuPHZaef/Ff8V4dlmEf+EuZiZhZzkUJ5p6goMAjS1px7ZEJdM3tJ1C82/lliCN7IitqQWJ2Q/Z1JZE0BPNays9X6sIertoDIxveo63kGay2RiFRsvZMyvM8ccsj+g5bmsQCQtbH1aBJehXO3XiXjDwaspp2PProKlecA/nqjI8NjoVQgmcyJbcH0=
